In [2]:
import json

with open('챔피언정보', 'r', encoding='utf-8') as file:
    champs = json.load(file)

with open('롤아이템템', 'r', encoding='utf-8') as file:
    items = json.load(file)

In [8]:
champs_list = []
for x in champs['data']:
    champs_list.append((champs['data'][x]['key'], champs['data'][x]['name'], champs['data'][x]['tags']))

champs_list

[('266', '아트록스', ['Fighter']),
 ('103', '아리', ['Mage', 'Assassin']),
 ('84', '아칼리', ['Assassin']),
 ('166', '아크샨', ['Marksman', 'Assassin']),
 ('12', '알리스타', ['Tank', 'Support']),
 ('32', '아무무', ['Tank', 'Support']),
 ('34', '애니비아', ['Mage']),
 ('1', '애니', ['Mage', 'Support']),
 ('523', '아펠리오스', ['Marksman']),
 ('22', '애쉬', ['Marksman', 'Support']),
 ('136', '아우렐리온 솔', ['Mage']),
 ('893', '오로라', ['Mage', 'Assassin']),
 ('268', '아지르', ['Mage', 'Marksman']),
 ('432', '바드', ['Support', 'Mage']),
 ('200', '벨베스', ['Fighter']),
 ('53', '블리츠크랭크', ['Tank', 'Support']),
 ('63', '브랜드', ['Mage', 'Support']),
 ('201', '브라움', ['Tank', 'Support']),
 ('233', '브라이어', ['Fighter', 'Assassin']),
 ('51', '케이틀린', ['Marksman']),
 ('164', '카밀', ['Fighter', 'Assassin']),
 ('69', '카시오페아', ['Mage']),
 ('31', '초가스', ['Tank', 'Mage']),
 ('42', '코르키', ['Marksman', 'Mage']),
 ('122', '다리우스', ['Fighter', 'Tank']),
 ('131', '다이애나', ['Fighter', 'Assassin']),
 ('119', '드레이븐', ['Marksman']),
 ('36', '문도 박사', ['Tank', 'Fighter']),
 ('245', '에코', ['Assassin', 'Mage']),
 ('60', '엘리스', ['Assassin', 'Mage']),
 ('28', '이블린', ['Assassin', 'Mage']),
 ('81', '이즈리얼', ['Marksman', 'Mage']),
 ('9', '피들스틱', ['Mage', 'Support']),
 ('114', '피오라', ['Fighter', 'Assassin']),
 ('105', '피즈', ['Assassin', 'Fighter']),
 ('3', '갈리오', ['Tank', 'Mage']),
 ('41', '갱플랭크', ['Fighter']),
 ('86', '가렌', ['Fighter', 'Tank']),
 ('150', '나르', ['Fighter', 'Tank']),
 ('79', '그라가스', ['Fighter', 'Mage']),
 ('104', '그레이브즈', ['Marksman']),
 ('887', '그웬', ['Fighter']),
 ('120', '헤카림', ['Fighter', 'Tank']),
 ('74', '하이머딩거', ['Mage', 'Support']),
 ('910', '흐웨이', ['Mage', 'Support']),
 ('420', '일라오이', ['Fighter', 'Tank']),
 ('39', '이렐리아', ['Fighter', 'Assassin']),
 ('427', '아이번', ['Support', 'Mage']),
 ('40', '잔나', ['Support', 'Mage']),
 ('59', '자르반 4세', ['Fighter', 'Tank']),
 ('24', '잭스', ['Fighter']),
 ('126', '제이스', ['Marksman', 'Fighter']),
 ('202', '진', ['Marksman', 'Mage']),
 ('222', '징크스', ['Marksman']),
 ('145', '카이사', ['Marksman', 'Mage']),
 ('429', '칼리스타', ['Marksman']),
 ('43', '카르마', ['Mage', 'Support']),
 ('30', '카서스', ['Mage']),
 ('38', '카사딘', ['Assassin', 'Mage']),
 ('55', '카타리나', ['Assassin', 'Mage']),
 ('10', '케일', ['Mage', 'Marksman']),
 ('141', '케인', ['Fighter', 'Assassin']),
 ('85', '케넨', ['Mage']),
 ('121', '카직스', ['Assassin']),
 ('203', '킨드레드', ['Marksman']),
 ('240', '클레드', ['Fighter']),
 ('96', '코그모', ['Marksman', 'Mage']),
 ('897', '크산테', ['Tank', 'Fighter']),
 ('7', '르블랑', ['Assassin', 'Mage']),
 ('64', '리 신', ['Fighter', 'Assassin']),
 ('89', '레오나', ['Tank', 'Support']),
 ('876', '릴리아', ['Fighter', 'Mage']),
 ('127', '리산드라', ['Mage']),
 ('236', '루시안', ['Marksman', 'Assassin']),
 ('117', '룰루', ['Support', 'Mage']),
 ('99', '럭스', ['Mage', 'Support']),
 ('54', '말파이트', ['Tank', 'Mage']),
 ('90', '말자하', ['Mage']),
 ('57', '마오카이', ['Tank', 'Support']),
 ('11', '마스터 이', ['Assassin', 'Fighter']),
 ('902', '밀리오', ['Support', 'Mage']),
 ('21', '미스 포츈', ['Marksman', 'Mage']),
 ('62', '오공', ['Fighter', 'Tank']),
 ('82', '모데카이저', ['Fighter', 'Mage']),
 ('25', '모르가나', ['Mage', 'Support']),
 ('950', '나피리', ['Assassin', 'Fighter']),
 ('267', '나미', ['Support', 'Mage']),
 ('75', '나서스', ['Fighter', 'Tank']),
 ('111', '노틸러스', ['Tank', 'Support']),
 ('518', '니코', ['Mage', 'Support']),
 ('76', '니달리', ['Assassin', 'Mage']),
 ('895', '닐라', ['Fighter', 'Assassin']),
 ('56', '녹턴', ['Fighter', 'Assassin']),
 ('20', '누누와 윌럼프', ['Tank', 'Mage']),
 ('2', '올라프', ['Fighter', 'Tank']),
 ('61', '오리아나', ['Mage', 'Support']),
 ('516', '오른', ['Tank']),
 ('80', '판테온', ['Fighter', 'Assassin']),
 ('78', '뽀삐', ['Tank', 'Fighter']),
 ('555', '파이크', ['Support', 'Assassin']),
 ('246', '키아나', ['Assassin']),
 ('133', '퀸', ['Marksman', 'Assassin']),
 ('497', '라칸', ['Support']),
 ('33', '람머스', ['Tank']),
 ('421', '렉사이', ['Fighter', 'Tank']),
 ('526', '렐', ['Tank', 'Support']),
 ('888', '레나타 글라스크', ['Support', 'Mage']),
 ('58', '레넥톤', ['Fighter', 'Tank']),
 ('107', '렝가', ['Assassin', 'Fighter']),
 ('92', '리븐', ['Fighter', 'Assassin']),
 ('68', '럼블', ['Fighter', 'Mage']),
 ('13', '라이즈', ['Mage']),
 ('360', '사미라', ['Marksman', 'Assassin']),
 ('113', '세주아니', ['Tank']),
 ('235', '세나', ['Support', 'Marksman']),
 ('147', '세라핀', ['Support', 'Mage']),
 ('875', '세트', ['Fighter', 'Tank']),
 ('35', '샤코', ['Assassin']),
 ('98', '쉔', ['Tank']),
 ('102', '쉬바나', ['Fighter', 'Mage']),
 ('27', '신지드', ['Tank', 'Mage']),
 ('14', '사이온', ['Tank', 'Fighter']),
 ('15', '시비르', ['Marksman']),
 ('72', '스카너', ['Tank', 'Fighter']),
 ('901', '스몰더', ['Marksman', 'Mage']),
 ('37', '소나', ['Support', 'Mage']),
 ('16', '소라카', ['Support', 'Mage']),
 ('50', '스웨인', ['Mage', 'Support']),
 ('517', '사일러스', ['Mage', 'Assassin']),
 ('134', '신드라', ['Mage']),
 ('223', '탐 켄치', ['Tank', 'Support']),
 ('163', '탈리야', ['Mage', 'Support']),
 ('91', '탈론', ['Assassin']),
 ('44', '타릭', ['Support', 'Tank']),
 ('17', '티모', ['Marksman', 'Mage']),
 ('412', '쓰레쉬', ['Support', 'Tank']),
 ('18', '트리스타나', ['Marksman', 'Assassin']),
 ('48', '트런들', ['Fighter', 'Tank']),
 ('23', '트린다미어', ['Fighter', 'Assassin']),
 ('4', '트위스티드 페이트', ['Mage', 'Marksman']),
 ('29', '트위치', ['Marksman', 'Assassin']),
 ('77', '우디르', ['Fighter', 'Tank']),
 ('6', '우르곳', ['Fighter', 'Tank']),
 ('110', '바루스', ['Marksman', 'Mage']),
 ('67', '베인', ['Marksman', 'Assassin']),
 ('45', '베이가', ['Mage']),
 ('161', '벨코즈', ['Mage', 'Support']),
 ('711', '벡스', ['Mage']),
 ('254', '바이', ['Fighter', 'Assassin']),
 ('234', '비에고', ['Fighter', 'Assassin']),
 ('112', '빅토르', ['Mage']),
 ('8', '블라디미르', ['Mage', 'Fighter']),
 ('106', '볼리베어', ['Fighter', 'Tank']),
 ('19', '워윅', ['Fighter', 'Tank']),
 ('498', '자야', ['Marksman']),
 ('101', '제라스', ['Mage', 'Support']),
 ('5', '신 짜오', ['Fighter', 'Tank']),
 ('157', '야스오', ['Fighter', 'Assassin']),
 ('777', '요네', ['Fighter', 'Assassin']),
 ('83', '요릭', ['Fighter', 'Tank']),
 ('350', '유미', ['Support', 'Mage']),
 ('154', '자크', ['Tank', 'Fighter']),
 ('238', '제드', ['Assassin']),
 ('221', '제리', ['Marksman']),
 ('115', '직스', ['Mage']),
 ('26', '질리언', ['Support', 'Mage']),
 ('142', '조이', ['Mage']),
 ('143', '자이라', ['Mage', 'Support'])]

In [6]:
import pandas as pd

In [10]:
cdf = pd.DataFrame(champs_list)
cdf.columns = ['key', 'name', 'tags']
cdf = cdf.set_index('key').sort_values('name')
cdf

      name                 tags
key
86      가렌      [Fighter, Tank]
3      갈리오         [Tank, Mage]
41    갱플랭크            [Fighter]
79    그라가스      [Fighter, Mage]
104  그레이브즈           [Marksman]
..     ...                  ...
114    피오라  [Fighter, Assassin]
105     피즈  [Assassin, Fighter]
74   하이머딩거      [Mage, Support]
120    헤카림      [Fighter, Tank]
910    흐웨이      [Mage, Support]

[168 rows x 2 columns]

In [12]:
cdf.to_csv('챔프사전.csv', encoding='utf-8')

In [19]:
items_list = []
for x in items['data']:
    items_list.append((x, items['data'][x]['name']))

items_list

[('1001', '장화'),
 ('1004', '요정의 부적'),
 ('1006', '원기 회복의 구슬'),
 ('1011', '거인의 허리띠'),
 ('1018', '민첩성의 망토'),
 ('1026', '방출의 마법봉'),
 ('1027', '사파이어 수정'),
 ('1028', '루비 수정'),
 ('1029', '천 갑옷'),
 ('1031', '쇠사슬 조끼'),
 ('1033', '마법무효화의 망토'),
 ('1035', '잉걸불 칼'),
 ('1036', '롱소드'),
 ('1037', '곡괭이'),
 ('1038', 'B.F. 대검'),
 ('1039', '빗발칼날'),
 ('1040', '흑요석 검'),
 ('1042', '단검'),
 ('1043', '곡궁'),
 ('1052', '증폭의 고서'),
 ('1053', '흡혈의 낫'),
 ('1054', '도란의 방패'),
 ('1055', '도란의 검'),
 ('1056', '도란의 반지'),
 ('1057', '음전자 망토'),
 ('1058', '쓸데없이 큰 지팡이'),
 ('1082', '암흑의 인장'),
 ('1083', '수확의 낫'),
 ('1101', '새끼 화염발톱'),
 ('1102', '새끼 바람돌이'),
 ('1103', '새끼 이끼쿵쿵이'),
 ('1104', '전령의 눈'),
 ('1105', '새끼 이끼쿵쿵이'),
 ('1106', '새끼 바람돌이'),
 ('1107', '새끼 화염발톱'),
 ('126697', '오만<br>'),
 ('1500', '관통 탄환'),
 ('1501', '요새화'),
 ('1502', '이중 갑옷'),
 ('1503', '파수꾼의 눈'),
 ('1504', '수호자'),
 ('1506', '이중 갑옷'),
 ('1507', '과충전'),
 ('1508', '방탄 양말'),
 ('1509', '체질'),
 ('1510', '특이 체질'),
 ('1511', '슈퍼 메크 방어구'),
 ('1512', '슈퍼 메크 전력장'),
 ('1515', '포탑 방패'),
 ('1516', '구조물 현상금'),
 ('1517', '구조물 현상금'),
 ('1518', '구조물 현상금'),
 ('1519', '구조물 현상금'),
 ('1520', '과충전HA'),
 ('1521', '요새화'),
 ('1522', '포탑 강화'),
 ('2003', '체력 물약'),
 ('2010', '굳건한 의지의 완전한 비스킷'),
 ('2015', '키르히아이스의 파편'),
 ('2019', '강철 인장'),
 ('2020', '야수화'),
 ('2021', '땅굴 채굴기'),
 ('2022', '빛나는 티끌'),
 ('2031', '충전형 물약'),
 ('2033', '부패 물약'),
 ('2049', '수호자의 부적'),
 ('2050', '수호자의 장막'),
 ('2051', '수호자의 뿔피리'),
 ('2052', '포로 간식'),
 ('2055', '제어 와드'),
 ('2056', '투명 와드'),
 ('2065', '슈렐리아의 군가'),
 ('2138', '강철의 영약'),
 ('2139', '마법의 영약'),
 ('2140', '분노의 영약'),
 ('2141', '카파 주스'),
 ('2142', '힘의 주스'),
 ('2143', '활력의 주스'),
 ('2144', '가속의 주스'),
 ('2145', '행운의 주사위'),
 ('2150', '숙련의 영약'),
 ('2151', '탐욕의 영약'),
 ('2152', '힘의 영약'),
 ('220000', '추가 능력치'),
 ('220001', '전설 전사 아이템'),
 ('220002', '전설 원거리 딜러 아이템'),
 ('220003', '전설 암살자 아이템'),
 ('220004', '전설 마법사 아이템'),
 ('220005', '전설 탱커 아이템'),
 ('220006', '전설 서포터 아이템'),
 ('220007', '프리즘 아이템'),
 ('221011', '거인의 허리띠'),
 ('221026', '방출의 마법봉'),
 ('221031', '쇠사슬 조끼'),
 ('221038', 'B.F. 대검'),
 ('221043', '곡궁'),
 ('221053', '흡혈의 낫'),
 ('221057', '음전자 망토'),
 ('221058', '쓸데없이 큰 지팡이'),
 ('222022', '빛나는 티끌'),
 ('222051', '수호자의 뿔피리'),
 ('222065', '슈렐리아의 군가'),
 ('222141', '카파 주스'),
 ('222502', '끝없는 절망'),
 ('222503', '어둠불꽃 횃불'),
 ('222504', '케이닉 루컨'),
 ('223001', '저녁갑주'),
 ('223002', '개척자'),
 ('223003', '대천사의 지팡이'),
 ('223004', '마나무네'),
 ('223005', '유령 배회자'),
 ('223006', '광전사의 군화'),
 ('223009', '신속의 장화'),
 ('223011', '화학공학 부패기'),
 ('223020', '마법사의 신발'),
 ('223026', '수호 천사'),
 ('223031', '무한의 대검'),
 ('223032', '윤 탈 야생화살'),
 ('223033', '필멸자의 운명'),
 ('223036', '도미닉 경의 인사'),
 ('223039', '아트마의 심판'),
 ('223040', '대천사의 포옹'),
 ('223042', '무라마나'),
 ('223046', '유령 무희'),
 ('223047', '판금 장화'),
 ('223050', '지크의 융합'),
 ('223053', '스테락의 도전'),
 ('223057', '광휘의 검'),
 ('223065', '정령의 형상'),
 ('223067', '점화석'),
 ('223068', '태양불꽃 방패'),
 ('223071', '칠흑의 양날 도끼'),
 ('223072', '피바라기'),
 ('223073', '실험적 마공학판'),
 ('223074', '굶주린 히드라'),
 ('223075', '가시 갑옷'),
 ('223078', '삼위일체'),
 ('223084', '강철심장'),
 ('223085', '루난의 허리케인'),
 ('223087', '스태틱의 단검'),
 ('223089', '라바돈의 죽음모자'),
 ('223091', '마법사의 최후'),
 ('223094', '고속 연사포'),
 ('223095', '폭풍갈퀴'),
 ('223100', '리치베인'),
 ('223102', '밴시의 장막'),
 ('223105', '군단의 방패'),
 ('223107', '구원'),
 ('223109', '기사의 맹세'),
 ('223110', '얼어붙은 심장'),
 ('223111', '헤르메스의 발걸음'),
 ('223112', '수호자의 보주'),
 ('223115', '내셔의 이빨'),
 ('223116', '라일라이의 수정홀'),
 ('223118', '악의'),
 ('223119', '혹한의 손길'),
 ('223121', '종말의 겨울'),
 ('223124', '구인수의 격노검'),
 ('223135', '공허의 지팡이'),
 ('223137', '무덤꽃'),
 ('223139', '헤르메스의 시미터'),
 ('223142', '요우무의 유령검'),
 ('223143', '란두인의 예언'),
 ('223146', '마법공학 총검'),
 ('223152', '마법공학 로켓 벨트'),
 ('223153', '몰락한 왕의 검'),
 ('223156', '맬모셔스의 아귀'),
 ('223157', '존야의 모래시계'),
 ('223158', '명석함의 아이오니아 장화'),
 ('223161', '쇼진의 창'),
 ('223165', '모렐로노미콘'),
 ('223172', '서풍'),
 ('223177', '수호자의 검'),
 ('223181', '선체파괴자'),
 ('223184', '수호자의 망치'),
 ('223185', '수호자의 단검'),
 ('223190', '강철의 솔라리 펜던트'),
 ('223193', '가고일 돌갑옷'),
 ('223222', '미카엘의 축복'),
 ('223302', '경계'),
 ('223504', '불타는 향로'),
 ('223508', '정수 약탈자'),
 ('223742', '망자의 갑옷'),
 ('223748', '거대한 히드라'),
 ('223814', '밤의 끝자락'),
 ('224004', '망령 해적검'),
 ('224005', '제국의 명령'),
 ('224401', '대자연의 힘'),
 ('224403', '황금 뒤집개'),
 ('224628', '지평선의 초점'),
 ('224629', '우주의 추진력'),
 ('224633', '균열 생성기'),
 ('224636', '밤의 수확자'),
 ('224637', '악마의 포옹'),
 ('224644', '부서진 여왕의 왕관'),
 ('224645', '그림자불꽃'),
 ('224646', '폭풍 쇄도'),
 ('226035', '은빛 여명'),
 ('226333', '죽음의 무도'),
 ('226609', '화공 펑크 사슬검'),
 ('226610', '갈라진 하늘'),
 ('226616', '흐르는 물의 지팡이'),
 ('226617', '월석 재생기'),
 ('226620', '헬리아의 메아리'),
 ('226621', '새벽심장'),
 ('226630', '선혈포식자'),
 ('226631', '발걸음 분쇄기'),
 ('226632', '신성한 파괴자'),
 ('226653', '리안드리의 고통'),
 ('226655', '루덴의 동반자'),
 ('226656', '만년서리'),
 ('226657', '영겁의 지팡이'),
 ('226662', '얼어붙은 건틀릿'),
 ('226664', '공허한 광휘'),
 ('226665', '해신 작쇼'),
 ('226667', '광휘의 미덕'),
 ('226671', '돌풍'),
 ('226672', '크라켄 학살자'),
 ('226673', '불멸의 철갑궁'),
 ('226675', '나보리 명멸검'),
 ('226676', '징수의 총'),
 ('226691', '드락사르의 황혼검'),
 ('226692', '월식'),
 ('226693', '자객의 발톱'),
 ('226694', '세릴다의 원한'),
 ('226695', '독사의 송곳니'),
 ('226696', '원칙의 원형낫'),
 ('226697', '오만'),
 ('226698', '불경한 히드라'),
 ('226699', '벼락폭풍검'),
 ('226701', '기회'),
 ('228001', '증오의 사슬'),
 ('228002', '우글렛의 마녀 모자'),
 ('228003', '죽음의 검'),
 ('228004', '적응형 투구'),
 ('228005', '흑요석 양날 도끼'),
 ('228006', '핏빛 칼날'),
 ('228008', '룬 글레이브'),
 ('228020', '심연의 가면'),
 ('2403', '미니언 해체분석기'),
 ('2420', '추적자의 팔목 보호대'),
 ('2421', '부서진 팔목 보호대'),
 ('2422', '약간 신비한 신발'),
 ('2501', '지배자의 피갑옷'),
 ('2502', '끝없는 절망'),
 ('2503', '어둠불꽃 횃불'),
 ('2504', '케이닉 루컨'),
 ('2508', '운명의 재'),
 ('3001', '저녁갑주'),
 ('3002', '개척자'),
 ('3003', '대천사의 지팡이'),
 ('3004', '마나무네'),
 ('3005', '유령 배회자'),
 ('3006', '광전사의 군화'),
 ('3009', '신속의 장화'),
 ('3010', '공생형 밑창'),
 ('3011', '화학공학 부패기'),
 ('3012', '축복의 성배'),
 ('3013', '하나 된 영혼'),
 ('3020', '마법사의 신발'),
 ('3023', '생명의 샘 펜던트'),
 ('3024', '얼음 방패'),
 ('3026', '수호 천사'),
 ('3031', '무한의 대검'),
 ('3032', '윤 탈 야생화살'),
 ('3033', '필멸자의 운명'),
 ('3035', '최후의 속삭임'),
 ('3036', '도미닉 경의 인사'),
 ('3039', '아트마의 심판'),
 ('3040', '대천사의 포옹'),
 ('3041', '메자이의 영혼약탈자'),
 ('3042', '무라마나'),
 ('3044', '탐식의 망치'),
 ('3046', '유령 무희'),
 ('3047', '판금 장화'),
 ('3050', '지크의 융합'),
 ('3051', '온기가 필요한 자의 도끼'),
 ('3053', '스테락의 도전'),
 ('3057', '광휘의 검'),
 ('3065', '정령의 형상'),
 ('3066', '비상의 월갑'),
 ('3067', '점화석'),
 ('3068', '태양불꽃 방패'),
 ('3070', '여신의 눈물'),
 ('3071', '칠흑의 양날 도끼'),
 ('3072', '피바라기'),
 ('3073', '실험적 마공학판'),
 ('3074', '굶주린 히드라'),
 ('3075', '가시 갑옷'),
 ('3076', '덤불 조끼'),
 ('3077', '티아맷'),
 ('3078', '삼위일체'),
 ('3082', '파수꾼의 갑옷'),
 ('3083', '워모그의 갑옷'),
 ('3084', '강철심장'),
 ('3085', '루난의 허리케인'),
 ('3086', '열정의 검'),
 ('3087', '스태틱의 단검'),
 ('3089', '라바돈의 죽음모자'),
 ('3091', '마법사의 최후'),
 ('3094', '고속 연사포'),
 ('3095', '폭풍갈퀴'),
 ('3100', '리치베인'),
 ('3102', '밴시의 장막'),
 ('3105', '군단의 방패'),
 ('3107', '구원'),
 ('3108', '악마의 마법서'),
 ('3109', '기사의 맹세'),
 ('3110', '얼어붙은 심장'),
 ('3111', '헤르메스의 발걸음'),
 ('3112', '수호자의 보주'),
 ('3113', '에테르 환영'),
 ('3114', '금지된 우상'),
 ('3115', '내셔의 이빨'),
 ('3116', '라일라이의 수정홀'),
 ('3117', '기동력의 장화'),
 ('3118', '악의'),
 ('3119', '혹한의 손길'),
 ('3121', '종말의 겨울'),
 ('3123', '처형인의 대검'),
 ('3124', '구인수의 격노검'),
 ('3128', '죽음불꽃 손아귀'),
 ('3131', '신성의 검'),
 ('3133', '콜필드의 전투 망치'),
 ('3134', '톱날 단검'),
 ('3135', '공허의 지팡이'),
 ('3137', '무덤꽃'),
 ('3139', '헤르메스의 시미터'),
 ('3140', '수은 장식띠'),
 ('3142', '요우무의 유령검'),
 ('3143', '란두인의 예언'),
 ('3144', '정찰병의 새총'),
 ('3145', '마법공학 교류 발전기'),
 ('3146', '마법공학 총검'),
 ('3147', '기괴한 가면'),
 ('3152', '마법공학 로켓 벨트'),
 ('3153', '몰락한 왕의 검'),
 ('3155', '주문포식자'),
 ('3156', '맬모셔스의 아귀'),
 ('3157', '존야의 모래시계'),
 ('3158', '명석함의 아이오니아 장화'),
 ('3161', '쇼진의 창'),
 ('3165', '모렐로노미콘'),
 ('3172', '서풍'),
 ('3177', '수호자의 검'),
 ('3179', '그림자 검'),
 ('3181', '선체파괴자'),
 ('3184', '수호자의 망치'),
 ('3190', '강철의 솔라리 펜던트'),
 ('3193', '가고일 돌갑옷'),
 ('3211', '망령의 두건'),
 ('3222', '미카엘의 축복'),
 ('3302', '경계'),
 ('3330', '허수아비'),
 ('3340', '투명 와드'),
 ('3348', '비전 탐지기'),
 ('3349', '광휘의 특이점'),
 ('3363', '망원형 개조'),
 ('3364', '예언자의 렌즈'),
 ('3400', '수당'),
 ('3430', '파멸의식 고서'),
 ('3504', '불타는 향로'),
 ('3508', '정수 약탈자'),
 ('3513', '전령의 눈'),
 ('3599', '칼리스타의 칠흑의 창'),
 ('3600', '칼리스타의 칠흑의 창'),
 ('3742', '망자의 갑옷'),
 ('3748', '거대한 히드라'),
 ('3801', '수정 팔 보호구'),
 ('3802', '사라진 양피지'),
 ('3803', '억겁의 카탈리스트'),
 ('3814', '밤의 끝자락'),
 ('3850', '주문도둑의 검'),
 ('3851', '얼음 송곳니'),
 ('3853', '얼음 정수의 파편'),
 ('3854', '강철 어깨 보호대'),
 ('3855', '룬 강철 어깨 갑옷'),
 ('3857', '화이트록의 갑옷'),
 ('3858', '고대유물 방패'),
 ('3859', '타곤 산의 방패'),
 ('3860', '타곤 산의 방벽'),
 ('3862', '영혼의 낫'),
 ('3863', '해로윙 초승달낫'),
 ('3864', '검은 안개 낫'),
 ('3865', '세계 지도집'),
 ('3866', '룬 나침반'),
 ('3867', '세계의 결실'),
 ('3869', '천상의 이의'),
 ('3870', '꿈 생성기'),
 ('3871', '자자크의 세계가시'),
 ('3876', '태양의 썰매'),
 ('3877', '피의 노래'),
 ('3901',
  '<rarityLegendary>가차없는 포격</rarityLegendary><br><subtitleLeft><silver>바다뱀 은화 500닢</silver></subtitleLeft>'),
 ('3902',
  '<rarityLegendary>죽음의 여신</rarityLegendary><br><subtitleLeft><silver>바다뱀 은화 500닢</silver></subtitleLeft>'),
 ('3903',
  '<rarityLegendary>사기진작</rarityLegendary><br><subtitleLeft><silver>바다뱀 은화 500닢</silver></subtitleLeft>'),
 ('3916', '망각의 구'),
 ('4003', '생명선'),
 ('4004', '망령 해적검'),
 ('4005', '제국의 명령'),
 ('4010', '핏빛 저주'),
 ('4011', '꽃피는 새벽의 검'),
 ('4012', '죄악 포식자'),
 ('4013', '번개 끈'),
 ('4014', '얼어붙은 망치'),
 ('4015', '당혹'),
 ('4016', '무언의 서약'),
 ('4017', '지옥불 손도끼'),
 ('4401', '대자연의 힘'),
 ('4402', '활력증진의 펜던트'),
 ('4403', '황금 뒤집개'),
 ('443054', '흑강철 발톱'),
 ('443055', '질책'),
 ('443056', '불사대마왕의 왕관'),
 ('443058', '용암의 방패'),
 ('443059', '별빛밤 망토'),
 ('443060', '신성의 검'),
 ('443061', '엔트로피의 힘'),
 ('443062', '핏빛 선물'),
 ('443063', '일라이자의 기적'),
 ('443064', '승천의 부적'),
 ('443069', '불귀신'),
 ('443079', '터보 화공 탱크'),
 ('443080', '쌍둥이 가면'),
 ('443081', '마공화살 동료'),
 ('443090', '사신의 대가'),
 ('443193', '가고일 돌갑옷'),
 ('444636', '밤의 수확자'),
 ('444637', '악마의 포옹'),
 ('444644', '부서진 여왕의 왕관'),
 ('446632', '신성한 파괴자'),
 ('446656', '만년서리'),
 ('446667', '광휘의 미덕'),
 ('446671', '돌풍'),
 ('446691', '드락사르의 황혼검'),
 ('446693', '자객의 발톱'),
 ('447100', '신기루 검'),
 ('447101', '도박꾼의 칼날'),
 ('447102', '현실 균열'),
 ('447103', '혈마법사의 투구'),
 ('447104', '활력증진의 펜던트'),
 ('447105', '창공의 서약'),
 ('447106', '용의 심장'),
 ('447107', '참수자'),
 ('447108', '룬 조각기'),
 ('447109', '잔혹 행위'),
 ('447110', '달빛 마법검'),
 ('447111', '지배자의 피갑옷'),
 ('447112', '살점포식자'),
 ('447113', '폭발의 구'),
 ('447114', '반향'),
 ('447115', '섭정 시해'),
 ('447116', '킨코우 십수'),
 ('447118', '화염술사의 망토'),
 ('447119', '번개 막대'),
 ('447120', '다이아몬드 창'),
 ('447121', '황혼의 끝자락'),
 ('447122', '블랙홀 건틀릿'),
 ('447123', '조종의 손아귀'),
 ('4628', '지평선의 초점'),
 ('4629', '우주의 추진력'),
 ('4630', '역병의 보석'),
 ('4632', '신록의 장벽'),
 ('4633', '균열 생성기'),
 ('4635', '흡수의 시선'),
 ('4636', '밤의 수확자'),
 ('4637', '악마의 포옹'),
 ('4638', '감시하는 와드석'),
 ('4641', '고무의 와드석'),
 ('4642', '밴들유리 거울'),
 ('4643', '경계의 와드석'),
 ('4644', '부서진 여왕의 왕관'),
 ('4645', '그림자불꽃'),
 ('4646', '폭풍 쇄도'),
 ('6029', '강철가시 채찍'),
 ('6035', '은빛 여명'),
 ('6333', '죽음의 무도'),
 ('6609', '화공 펑크 사슬검'),
 ('6610', '갈라진 하늘'),
 ('6616', '흐르는 물의 지팡이'),
 ('6617', '월석 재생기'),
 ('6620', '헬리아의 메아리'),
 ('6621', '새벽심장'),
 ('6630', '선혈포식자'),
 ('6631', '발걸음 분쇄기'),
 ('6632', '신성한 파괴자'),
 ('6653', '리안드리의 고통'),
 ('6655', '루덴의 동반자'),
 ('6656', '만년서리'),
 ('6657', '영겁의 지팡이'),
 ('6660', '바미의 불씨'),
 ('6662', '얼어붙은 건틀릿'),
 ('6664', '공허한 광휘'),
 ('6665', '해신 작쇼'),
 ('6667', '광휘의 미덕'),
 ('6670', '절정의 화살'),
 ('6671', '돌풍'),
 ('6672', '크라켄 학살자'),
 ('6673', '불멸의 철갑궁'),
 ('6675', '나보리 명멸검'),
 ('6676', '징수의 총'),
 ('6677', '분노의 칼'),
 ('6690', '꽁지깃'),
 ('6691', '드락사르의 황혼검'),
 ('6692', '월식'),
 ('6693', '자객의 발톱'),
 ('6694', '세릴다의 원한'),
 ('6695', '독사의 송곳니'),
 ('6696', '원칙의 원형낫'),
 ('6697', '오만'),
 ('6698', '불경한 히드라'),
 ('6699', '벼락폭풍검'),
 ('6700', '라코어의 방패'),
 ('6701', '기회'),
 ('7050', '갱플랭크 Placeholder'),
 ('8001', '증오의 사슬'),
 ('8020', '심연의 가면'),
 ('9168', '잠긴 무기 슬롯'),
 ('9171', '회오리 칼날'),
 ('9172', '유미봇'),
 ('9173', '광휘 역장'),
 ('9174', '스태틱의 검'),
 ('9175', '사자의 비가'),
 ('9176', '개틀링 토끼 건'),
 ('9177', '타오르는 단궁'),
 ('9178', '절멸자'),
 ('9179', '전투 토끼 석궁'),
 ('9180', '귀여운 발사기'),
 ('9181', '소용돌이 장갑'),
 ('9183', '칼날 부메랑'),
 ('9184', '토끼 초강력 폭발'),
 ('9185', '상어잡이 해양 기뢰'),
 ('9187', '티.버'),
 ('9188', '동물 지뢰'),
 ('9189', '최후의 도시 대중교통'),
 ('9190', '메아리치는 박쥐칼날'),
 ('9192', '발자국 중독 장치'),
 ('9193', '얼음작렬 갑옷'),
 ('9271', '그치지 않는 폭풍'),
 ('9272', '유미봇_최종_최종'),
 ('9273', '폭발의 포옹'),
 ('9274', '프룸비스의 전기도축칼'),
 ('9275', '휘감는 빛'),
 ('9276', '이중 깡충깡충 포화'),
 ('9277', '진화한 불꽃 사격'),
 ('9278', '동물의 종말'),
 ('9279', '토끼 프라임 거대 석궁'),
 ('9280', '왕 귀여운 발사기'),
 ('9281', '폭풍의 건틀릿'),
 ('9283', '사중 부메랑'),
 ('9284', '고속 토끼 속사포'),
 ('9285', '무한의 괴물 퇴치기'),
 ('9287', '티.버 (특.대.형 에디션)'),
 ('9288', '징크스의 삼중 다이너마이트'),
 ('9289', 'FC 급행열차'),
 ('9290', '베인의 크로마칼날'),
 ('9292', '맨발 화학 물질 분사기'),
 ('9293', '완전 빙결'),
 ('9300', '야옹 야옹'),
 ('9301', '방패 타격'),
 ('9302', '음향의 물결'),
 ('9303', '족쇄 할퀴기'),
 ('9304', '강철 폭풍'),
 ('9305', '촉수 후려치기'),
 ('9306', '날개 달린 단검'),
 ('9307', '인도의 저주'),
 ('9308', '토끼뜀'),
 ('9400', '전투 고양이 총알 세례'),
 ('9401', '사자의 광명'),
 ('9402', '동물 메아리'),
 ('9403', '포악한 베기'),
 ('9404', '떠도는 폭풍'),
 ('9405', '곰의 강타'),
 ('9406', '연인의 도탄'),
 ('9407', '고양된 저주'),
 ('9408', '당근 격돌')]

In [21]:
idf = pd.DataFrame(items_list)
idf.columns = ['key', 'name']
idf = idf.set_index('key')
idf

           name
key
1001         장화
1004     요정의 부적
1006  원기 회복의 구슬
1011    거인의 허리띠
1018    민첩성의 망토
...         ...
9404     떠도는 폭풍
9405      곰의 강타
9406     연인의 도탄
9407     고양된 저주
9408      당근 격돌

[575 rows x 1 columns]

In [23]:
idf.to_csv('아이템사전.csv', encoding='utf-8')

In [7]:
import pandas as pd
import pymysql

In [3]:
cham_df = pd.read_csv('챔프사전.csv')

In [17]:
conn = pymysql.connect(
    host="localhost",
    user="root",
    password="1221"
)

cham_df.columns = ['champion_id', 'champion_name']
cham_df

cur = conn.cursor()
cur.execute('use LOL_data;')
for e in cham_df.iterrows():
    query = f'''insert into champion_dict (champion_id, champion_name) values ({e[1][0]}, '{e[1][1]}');'''
    cur.execute(query)
conn.commit()
cur.close()

C:\Users\건\AppData\Local\Temp\ipykernel_30344\2321677696.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  query = f'''insert into champion_dict (champion_id, champion_name) values ({e[1][0]}, '{e[1][1]}');'''

In [67]:
item_df = pd.read_csv('아이템사전.csv')
item_df.columns = ['item_id', 'item_name']
item_df

     item_id  item_name
0       1001         장화
1       1004     요정의 부적
2       1006  원기 회복의 구슬
3       1011    거인의 허리띠
4       1018    민첩성의 망토
..       ...        ...
570     9404     떠도는 폭풍
571     9405      곰의 강타
572     9406     연인의 도탄
573     9407     고양된 저주
574     9408      당근 격돌

[575 rows x 2 columns]

In [89]:
conn = pymysql.connect(
    host="localhost",
    user="root",
    password="1221"
)

cur = conn.cursor()
cur.execute('use LOL_data;')
for e in item_df.iterrows():
    print(e)
    query = f'''insert into item_dict (item_id, item_name) values ({e[1][0]}, '{e[1][1]}');'''
    cur.execute(query)

(0, item_id      1001
item_name      장화
Name: 0, dtype: object)
(1, item_id        1004
item_name    요정의 부적
Name: 1, dtype: object)
(2, item_id           1006
item_name    원기 회복의 구슬
Name: 2, dtype: object)
(3, item_id         1011
item_name    거인의 허리띠
Name: 3, dtype: object)
(4, item_id         1018
item_name    민첩성의 망토
Name: 4, dtype: object)
(5, item_id         1026
item_name    방출의 마법봉
Name: 5, dtype: object)
(6, item_id         1027
item_name    사파이어 수정
Name: 6, dtype: object)
(7, item_id       1028
item_name    루비 수정
Name: 7, dtype: object)
(8, item_id      1029
item_name    천 갑옷
Name: 8, dtype: object)
(9, item_id        1031
item_name    쇠사슬 조끼
Name: 9, dtype: object)
(10, item_id           1033
item_name    마법무효화의 망토
Name: 10, dtype: object)
(11, item_id       1035
item_name    잉걸불 칼
Name: 11, dtype: object)
(12, item_id      1036
item_name     롱소드
Name: 12, dtype: object)
(13, item_id      1037
item_name     곡괭이
Name: 13, dtype: object)
(14, item_id      1038
item_name      대검
Name: 14, dtype: object)
(15, item_id      1039
item_name    빗발칼날
Name: 15, dtype: object)
(16, item_id       1040
item_name    흑요석 검
Name: 16, dtype: object)
(17, item_id      1042
item_name      단검
Name: 17, dtype: object)
(18, item_id      1043
item_name      곡궁
Name: 18, dtype: object)
(19, item_id        1052
item_name    증폭의 고서
Name: 19, dtype: object)
(20, item_id       1053
item_name    흡혈의 낫
Name: 20, dtype: object)
(21, item_id        1054
item_name    도란의 방패
Name: 21, dtype: object)
(22, item_id       1055
item_name    도란의 검
Name: 22, dtype: object)
(23, item_id        1056
item_name    도란의 반지
Name: 23, dtype: object)
(24, item_id        1057
item_name    음전자 망토
Name: 24, dtype: object)
(25, item_id            1058
item_name    쓸데없이 큰 지팡이
Name: 25, dtype: object)
(26, item_id        1082
item_name    암흑의 인장
Name: 26, dtype: object)
(27, item_id       1083
item_name    수확의 낫
Name: 27, dtype: object)
(28, item_id         1101
item_name    새끼 화염발톱
Name: 28, dtype: object)
(29, item_id         1102
item_name    새끼 바람돌이
Name: 29, dtype: object)
(30, item_id          1103
item_name    새끼 이끼쿵쿵이
Name: 30, dtype: object)
(31, item_id       1104
item_name    전령의 눈
Name: 31, dtype: object)
(32, item_id          1105
item_name    새끼 이끼쿵쿵이
Name: 32, dtype: object)
(33, item_id         1106
item_name    새끼 바람돌이
Name: 33, dtype: object)
(34, item_id         1107
item_name    새끼 화염발톱
Name: 34, dtype: object)
(35, item_id      126697
item_name        오만
Name: 35, dtype: object)
(36, item_id       1500
item_name    관통 탄환
Name: 36, dtype: object)
(37, item_id      1501
item_name     요새화
Name: 37, dtype: object)
(38, item_id       1502
item_name    이중 갑옷
Name: 38, dtype: object)
(39, item_id        1503
item_name    파수꾼의 눈
Name: 39, dtype: object)
(40, item_id      1504
item_name     수호자
Name: 40, dtype: object)
(41, item_id       1506
item_name    이중 갑옷
Name: 41, dtype: object)
(42, item_id      1507
item_name     과충전
Name: 42, dtype: object)
(43, item_id       1508
item_name    방탄 양말
Name: 43, dtype: object)
(44, item_id      1509
item_name      체질
Name: 44, dtype: object)
(45, item_id       1510
item_name    특이 체질
Name: 45, dtype: object)
(46, item_id           1511
item_name    슈퍼 메크 방어구
Name: 46, dtype: object)
(47, item_id           1512
item_name    슈퍼 메크 전력장
Name: 47, dtype: object)
(48, item_id       1515
item_name    포탑 방패
Name: 48, dtype: object)
(49, item_id         1516
item_name    구조물 현상금
Name: 49, dtype: object)
(50, item_id         1517
item_name    구조물 현상금
Name: 50, dtype: object)
(51, item_id         1518
item_name    구조물 현상금
Name: 51, dtype: object)
(52, item_id         1519
item_name    구조물 현상금
Name: 52, dtype: object)
(53, item_id      1520
item_name     과충전
Name: 53, dtype: object)
(54, item_id      1521
item_name     요새화
Name: 54, dtype: object)
(55, item_id       1522
item_name    포탑 강화
Name: 55, dtype: object)
(56, item_id       2003
item_name    체력 물약
Name: 56, dtype: object)
(57, item_id                 2010
item_name    굳건한 의지의 완전한 비스킷
Name: 57, dtype: object)
(58, item_id            2015
item_name    키르히아이스의 파편
Name: 58, dtype: object)
(59, item_id       2019
item_name    강철 인장
Name: 59, dtype: object)
(60, item_id      2020
item_name     야수화
Name: 60, dtype: object)
(61, item_id        2021
item_name    땅굴 채굴기
Name: 61, dtype: object)
(62, item_id        2022
item_name    빛나는 티끌
Name: 62, dtype: object)
(63, item_id        2031
item_name    충전형 물약
Name: 63, dtype: object)
(64, item_id       2033
item_name    부패 물약
Name: 64, dtype: object)
(65, item_id         2049
item_name    수호자의 부적
Name: 65, dtype: object)
(66, item_id         2050
item_name    수호자의 장막
Name: 66, dtype: object)
(67, item_id          2051
item_name    수호자의 뿔피리
Name: 67, dtype: object)
(68, item_id       2052
item_name    포로 간식
Name: 68, dtype: object)
(69, item_id       2055
item_name    제어 와드
Name: 69, dtype: object)
(70, item_id       2056
item_name    투명 와드
Name: 70, dtype: object)
(71, item_id          2065
item_name    슈렐리아의 군가
Name: 71, dtype: object)
(72, item_id        2138
item_name    강철의 영약
Name: 72, dtype: object)
(73, item_id        2139
item_name    마법의 영약
Name: 73, dtype: object)
(74, item_id        2140
item_name    분노의 영약
Name: 74, dtype: object)
(75, item_id       2141
item_name    카파 주스
Name: 75, dtype: object)
(76, item_id       2142
item_name    힘의 주스
Name: 76, dtype: object)
(77, item_id        2143
item_name    활력의 주스
Name: 77, dtype: object)
(78, item_id        2144
item_name    가속의 주스
Name: 78, dtype: object)
(79, item_id         2145
item_name    행운의 주사위
Name: 79, dtype: object)
(80, item_id        2150
item_name    숙련의 영약
Name: 80, dtype: object)
(81, item_id        2151
item_name    탐욕의 영약
Name: 81, dtype: object)
(82, item_id       2152
item_name    힘의 영약
Name: 82, dtype: object)
(83, item_id      220000
item_name    추가 능력치
Name: 83, dtype: object)
(84, item_id         220001
item_name    전설 전사 아이템
Name: 84, dtype: object)
(85, item_id             220002
item_name    전설 원거리 딜러 아이템
Name: 85, dtype: object)
(86, item_id          220003
item_name    전설 암살자 아이템
Name: 86, dtype: object)
(87, item_id          220004
item_name    전설 마법사 아이템
Name: 87, dtype: object)
(88, item_id         220005
item_name    전설 탱커 아이템
Name: 88, dtype: object)
(89, item_id          220006
item_name    전설 서포터 아이템
Name: 89, dtype: object)
(90, item_id       220007
item_name    프리즘 아이템
Name: 90, dtype: object)
(91, item_id       221011
item_name    거인의 허리띠
Name: 91, dtype: object)
(92, item_id       221026
item_name    방출의 마법봉
Name: 92, dtype: object)
(93, item_id      221031
item_name    쇠사슬 조끼
Name: 93, dtype: object)
(94, item_id      221038
item_name        대검
Name: 94, dtype: object)
(95, item_id      221043
item_name        곡궁
Name: 95, dtype: object)
(96, item_id      221053
item_name     흡혈의 낫
Name: 96, dtype: object)
(97, item_id      221057
item_name    음전자 망토
Name: 97, dtype: object)
(98, item_id          221058
item_name    쓸데없이 큰 지팡이
Name: 98, dtype: object)
(99, item_id      222022
item_name    빛나는 티끌
Name: 99, dtype: object)
(100, item_id        222051
item_name    수호자의 뿔피리
Name: 100, dtype: object)
(101, item_id        222065
item_name    슈렐리아의 군가
Name: 101, dtype: object)
(102, item_id      222141
item_name     카파 주스
Name: 102, dtype: object)
(103, item_id      222502
item_name    끝없는 절망
Name: 103, dtype: object)
(104, item_id       222503
item_name    어둠불꽃 횃불
Name: 104, dtype: object)
(105, item_id      222504
item_name    케이닉 루컨
Name: 105, dtype: object)
(106, item_id      223001
item_name      저녁갑주
Name: 106, dtype: object)
(107, item_id      223002
item_name       개척자
Name: 107, dtype: object)
(108, item_id        223003
item_name    대천사의 지팡이
Name: 108, dtype: object)
(109, item_id      223004
item_name      마나무네
Name: 109, dtype: object)
(110, item_id      223005
item_name    유령 배회자
Name: 110, dtype: object)
(111, item_id       223006
item_name    광전사의 군화
Name: 111, dtype: object)
(112, item_id      223009
item_name    신속의 장화
Name: 112, dtype: object)
(113, item_id        223011
item_name    화학공학 부패기
Name: 113, dtype: object)
(114, item_id       223020
item_name    마법사의 신발
Name: 114, dtype: object)
(115, item_id      223026
item_name     수호 천사
Name: 115, dtype: object)
(116, item_id      223031
item_name    무한의 대검
Name: 116, dtype: object)
(117, item_id        223032
item_name    윤 탈 야생화살
Name: 117, dtype: object)
(118, item_id       223033
item_name    필멸자의 운명
Name: 118, dtype: object)
(119, item_id         223036
item_name    도미닉 경의 인사
Name: 119, dtype: object)
(120, item_id       223039
item_name    아트마의 심판
Name: 120, dtype: object)
(121, item_id       223040
item_name    대천사의 포옹
Name: 121, dtype: object)
(122, item_id      223042
item_name      무라마나
Name: 122, dtype: object)
(123, item_id      223046
item_name     유령 무희
Name: 123, dtype: object)
(124, item_id      223047
item_name     판금 장화
Name: 124, dtype: object)
(125, item_id      223050
item_name    지크의 융합
Name: 125, dtype: object)
(126, item_id       223053
item_name    스테락의 도전
Name: 126, dtype: object)
(127, item_id      223057
item_name     광휘의 검
Name: 127, dtype: object)
(128, item_id      223065
item_name    정령의 형상
Name: 128, dtype: object)
(129, item_id      223067
item_name       점화석
Name: 129, dtype: object)
(130, item_id       223068
item_name    태양불꽃 방패
Name: 130, dtype: object)
(131, item_id         223071
item_name    칠흑의 양날 도끼
Name: 131, dtype: object)
(132, item_id      223072
item_name      피바라기
Name: 132, dtype: object)
(133, item_id        223073
item_name    실험적 마공학판
Name: 133, dtype: object)
(134, item_id       223074
item_name    굶주린 히드라
Name: 134, dtype: object)
(135, item_id      223075
item_name     가시 갑옷
Name: 135, dtype: object)
(136, item_id      223078
item_name      삼위일체
Name: 136, dtype: object)
(137, item_id      223084
item_name      강철심장
Name: 137, dtype: object)
(138, item_id        223085
item_name    루난의 허리케인
Name: 138, dtype: object)
(139, item_id       223087
item_name    스태틱의 단검
Name: 139, dtype: object)
(140, item_id         223089
item_name    라바돈의 죽음모자
Name: 140, dtype: object)
(141, item_id       223091
item_name    마법사의 최후
Name: 141, dtype: object)
(142, item_id      223094
item_name    고속 연사포
Name: 142, dtype: object)
(143, item_id      223095
item_name      폭풍갈퀴
Name: 143, dtype: object)
(144, item_id      223100
item_name      리치베인
Name: 144, dtype: object)
(145, item_id      223102
item_name    밴시의 장막
Name: 145, dtype: object)
(146, item_id      223105
item_name    군단의 방패
Name: 146, dtype: object)
(147, item_id      223107
item_name        구원
Name: 147, dtype: object)
(148, item_id      223109
item_name    기사의 맹세
Name: 148, dtype: object)
(149, item_id       223110
item_name    얼어붙은 심장
Name: 149, dtype: object)
(150, item_id         223111
item_name    헤르메스의 발걸음
Name: 150, dtype: object)
(151, item_id       223112
item_name    수호자의 보주
Name: 151, dtype: object)
(152, item_id      223115
item_name    내셔의 이빨
Name: 152, dtype: object)
(153, item_id         223116
item_name    라일라이의 수정홀
Name: 153, dtype: object)
(154, item_id      223118
item_name        악의
Name: 154, dtype: object)
(155, item_id      223119
item_name    혹한의 손길
Name: 155, dtype: object)
(156, item_id      223121
item_name    종말의 겨울
Name: 156, dtype: object)
(157, item_id        223124
item_name    구인수의 격노검
Name: 157, dtype: object)
(158, item_id       223135
item_name    공허의 지팡이
Name: 158, dtype: object)
(159, item_id      223137
item_name       무덤꽃
Name: 159, dtype: object)
(160, item_id         223139
item_name    헤르메스의 시미터
Name: 160, dtype: object)
(161, item_id        223142
item_name    요우무의 유령검
Name: 161, dtype: object)
(162, item_id       223143
item_name    란두인의 예언
Name: 162, dtype: object)
(163, item_id       223146
item_name    마법공학 총검
Name: 163, dtype: object)
(164, item_id          223152
item_name    마법공학 로켓 벨트
Name: 164, dtype: object)
(165, item_id        223153
item_name    몰락한 왕의 검
Name: 165, dtype: object)
(166, item_id        223156
item_name    맬모셔스의 아귀
Name: 166, dtype: object)
(167, item_id        223157
item_name    존야의 모래시계
Name: 167, dtype: object)
(168, item_id             223158
item_name    명석함의 아이오니아 장화
Name: 168, dtype: object)
(169, item_id      223161
item_name     쇼진의 창
Name: 169, dtype: object)
(170, item_id      223165
item_name    모렐로노미콘
Name: 170, dtype: object)
(171, item_id      223172
item_name        서풍
Name: 171, dtype: object)
(172, item_id      223177
item_name    수호자의 검
Name: 172, dtype: object)
(173, item_id      223181
item_name     선체파괴자
Name: 173, dtype: object)
(174, item_id       223184
item_name    수호자의 망치
Name: 174, dtype: object)
(175, item_id       223185
item_name    수호자의 단검
Name: 175, dtype: object)
(176, item_id           223190
item_name    강철의 솔라리 펜던트
Name: 176, dtype: object)
(177, item_id       223193
item_name    가고일 돌갑옷
Name: 177, dtype: object)
(178, item_id       223222
item_name    미카엘의 축복
Name: 178, dtype: object)
(179, item_id      223302
item_name        경계
Name: 179, dtype: object)
(180, item_id      223504
item_name    불타는 향로
Name: 180, dtype: object)
(181, item_id      223508
item_name    정수 약탈자
Name: 181, dtype: object)
(182, item_id      223742
item_name    망자의 갑옷
Name: 182, dtype: object)
(183, item_id       223748
item_name    거대한 히드라
Name: 183, dtype: object)
(184, item_id      223814
item_name    밤의 끝자락
Name: 184, dtype: object)
(185, item_id      224004
item_name    망령 해적검
Name: 185, dtype: object)
(186, item_id      224005
item_name    제국의 명령
Name: 186, dtype: object)
(187, item_id      224401
item_name    대자연의 힘
Name: 187, dtype: object)
(188, item_id      224403
item_name    황금 뒤집개
Name: 188, dtype: object)
(189, item_id       224628
item_name    지평선의 초점
Name: 189, dtype: object)
(190, item_id       224629
item_name    우주의 추진력
Name: 190, dtype: object)
(191, item_id      224633
item_name    균열 생성기
Name: 191, dtype: object)
(192, item_id      224636
item_name    밤의 수확자
Name: 192, dtype: object)
(193, item_id      224637
item_name    악마의 포옹
Name: 193, dtype: object)
(194, item_id          224644
item_name    부서진 여왕의 왕관
Name: 194, dtype: object)
(195, item_id      224645
item_name     그림자불꽃
Name: 195, dtype: object)
(196, item_id      224646
item_name     폭풍 쇄도
Name: 196, dtype: object)
(197, item_id      226035
item_name     은빛 여명
Name: 197, dtype: object)
(198, item_id      226333
item_name    죽음의 무도
Name: 198, dtype: object)
(199, item_id         226609
item_name    화공 펑크 사슬검
Name: 199, dtype: object)
(200, item_id      226610
item_name    갈라진 하늘
Name: 200, dtype: object)
(201, item_id          226616
item_name    흐르는 물의 지팡이
Name: 201, dtype: object)
(202, item_id      226617
item_name    월석 재생기
Name: 202, dtype: object)
(203, item_id        226620
item_name    헬리아의 메아리
Name: 203, dtype: object)
(204, item_id      226621
item_name      새벽심장
Name: 204, dtype: object)
(205, item_id      226630
item_name     선혈포식자
Name: 205, dtype: object)
(206, item_id       226631
item_name    발걸음 분쇄기
Name: 206, dtype: object)
(207, item_id       226632
item_name    신성한 파괴자
Name: 207, dtype: object)
(208, item_id        226653
item_name    리안드리의 고통
Name: 208, dtype: object)
(209, item_id       226655
item_name    루덴의 동반자
Name: 209, dtype: object)
(210, item_id      226656
item_name      만년서리
Name: 210, dtype: object)
(211, item_id       226657
item_name    영겁의 지팡이
Name: 211, dtype: object)
(212, item_id        226662
item_name    얼어붙은 건틀릿
Name: 212, dtype: object)
(213, item_id      226664
item_name    공허한 광휘
Name: 213, dtype: object)
(214, item_id      226665
item_name     해신 작쇼
Name: 214, dtype: object)
(215, item_id      226667
item_name    광휘의 미덕
Name: 215, dtype: object)
(216, item_id      226671
item_name        돌풍
Name: 216, dtype: object)
(217, item_id       226672
item_name    크라켄 학살자
Name: 217, dtype: object)
(218, item_id       226673
item_name    불멸의 철갑궁
Name: 218, dtype: object)
(219, item_id       226675
item_name    나보리 명멸검
Name: 219, dtype: object)
(220, item_id      226676
item_name     징수의 총
Name: 220, dtype: object)
(221, item_id         226691
item_name    드락사르의 황혼검
Name: 221, dtype: object)
(222, item_id      226692
item_name        월식
Name: 222, dtype: object)
(223, item_id      226693
item_name    자객의 발톱
Name: 223, dtype: object)
(224, item_id       226694
item_name    세릴다의 원한
Name: 224, dtype: object)
(225, item_id       226695
item_name    독사의 송곳니
Name: 225, dtype: object)
(226, item_id       226696
item_name    원칙의 원형낫
Name: 226, dtype: object)
(227, item_id      226697
item_name        오만
Name: 227, dtype: object)
(228, item_id       226698
item_name    불경한 히드라
Name: 228, dtype: object)
(229, item_id      226699
item_name     벼락폭풍검
Name: 229, dtype: object)
(230, item_id      226701
item_name        기회
Name: 230, dtype: object)
(231, item_id      228001
item_name    증오의 사슬
Name: 231, dtype: object)
(232, item_id          228002
item_name    우글렛의 마녀 모자
Name: 232, dtype: object)
(233, item_id      228003
item_name     죽음의 검
Name: 233, dtype: object)
(234, item_id      228004
item_name    적응형 투구
Name: 234, dtype: object)
(235, item_id         228005
item_name    흑요석 양날 도끼
Name: 235, dtype: object)
(236, item_id      228006
item_name     핏빛 칼날
Name: 236, dtype: object)
(237, item_id      228008
item_name    룬 글레이브
Name: 237, dtype: object)
(238, item_id      228020
item_name    심연의 가면
Name: 238, dtype: object)
(239, item_id           2403
item_name    미니언 해체분석기
Name: 239, dtype: object)
(240, item_id             2420
item_name    추적자의 팔목 보호대
Name: 240, dtype: object)
(241, item_id            2421
item_name    부서진 팔목 보호대
Name: 241, dtype: object)
(242, item_id           2422
item_name    약간 신비한 신발
Name: 242, dtype: object)
(243, item_id          2501
item_name    지배자의 피갑옷
Name: 243, dtype: object)
(244, item_id        2502
item_name    끝없는 절망
Name: 244, dtype: object)
(245, item_id         2503
item_name    어둠불꽃 횃불
Name: 245, dtype: object)
(246, item_id        2504
item_name    케이닉 루컨
Name: 246, dtype: object)
(247, item_id       2508
item_name    운명의 재
Name: 247, dtype: object)
(248, item_id      3001
item_name    저녁갑주
Name: 248, dtype: object)
(249, item_id      3002
item_name     개척자
Name: 249, dtype: object)
(250, item_id          3003
item_name    대천사의 지팡이
Name: 250, dtype: object)
(251, item_id      3004
item_name    마나무네
Name: 251, dtype: object)
(252, item_id        3005
item_name    유령 배회자
Name: 252, dtype: object)
(253, item_id         3006
item_name    광전사의 군화
Name: 253, dtype: object)
(254, item_id        3009
item_name    신속의 장화
Name: 254, dtype: object)
(255, item_id        3010
item_name    공생형 밑창
Name: 255, dtype: object)
(256, item_id          3011
item_name    화학공학 부패기
Name: 256, dtype: object)
(257, item_id        3012
item_name    축복의 성배
Name: 257, dtype: object)
(258, item_id         3013
item_name    하나 된 영혼
Name: 258, dtype: object)
(259, item_id         3020
item_name    마법사의 신발
Name: 259, dtype: object)
(260, item_id           3023
item_name    생명의 샘 펜던트
Name: 260, dtype: object)
(261, item_id       3024
item_name    얼음 방패
Name: 261, dtype: object)
(262, item_id       3026
item_name    수호 천사
Name: 262, dtype: object)
(263, item_id        3031
item_name    무한의 대검
Name: 263, dtype: object)
(264, item_id          3032
item_name    윤 탈 야생화살
Name: 264, dtype: object)
(265, item_id         3033
item_name    필멸자의 운명
Name: 265, dtype: object)
(266, item_id         3035
item_name    최후의 속삭임
Name: 266, dtype: object)
(267, item_id           3036
item_name    도미닉 경의 인사
Name: 267, dtype: object)
(268, item_id         3039
item_name    아트마의 심판
Name: 268, dtype: object)
(269, item_id         3040
item_name    대천사의 포옹
Name: 269, dtype: object)
(270, item_id            3041
item_name    메자이의 영혼약탈자
Name: 270, dtype: object)
(271, item_id      3042
item_name    무라마나
Name: 271, dtype: object)
(272, item_id        3044
item_name    탐식의 망치
Name: 272, dtype: object)
(273, item_id       3046
item_name    유령 무희
Name: 273, dtype: object)
(274, item_id       3047
item_name    판금 장화
Name: 274, dtype: object)
(275, item_id        3050
item_name    지크의 융합

C:\Users\건\AppData\Local\Temp\ipykernel_30344\3467941270.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  query = f'''insert into item_dict (item_id, item_name) values ({e[1][0]}, '{e[1][1]}');'''

(504, item_id        6693
item_name    자객의 발톱
Name: 504, dtype: object)
(505, item_id         6694
item_name    세릴다의 원한
Name: 505, dtype: object)
(506, item_id         6695
item_name    독사의 송곳니
Name: 506, dtype: object)
(507, item_id         6696
item_name    원칙의 원형낫
Name: 507, dtype: object)
(508, item_id      6697
item_name      오만
Name: 508, dtype: object)
(509, item_id         6698
item_name    불경한 히드라
Name: 509, dtype: object)
(510, item_id       6699
item_name    벼락폭풍검
Name: 510, dtype: object)
(511, item_id         6700
item_name    라코어의 방패
Name: 511, dtype: object)
(512, item_id      6701
item_name      기회
Name: 512, dtype: object)
(513, item_id      7050
item_name    갱플랭크
Name: 513, dtype: object)
(514, item_id        8001
item_name    증오의 사슬
Name: 514, dtype: object)
(515, item_id        8020
item_name    심연의 가면
Name: 515, dtype: object)
(516, item_id          9168
item_name    잠긴 무기 슬롯
Name: 516, dtype: object)
(517, item_id        9171
item_name    회오리 칼날
Name: 517, dtype: object)
(518, item_id      9172
item_name     유미봇
Name: 518, dtype: object)
(519, item_id       9173
item_name    광휘 역장
Name: 519, dtype: object)
(520, item_id        9174
item_name    스태틱의 검
Name: 520, dtype: object)
(521, item_id        9175
item_name    사자의 비가
Name: 521, dtype: object)
(522, item_id          9176
item_name    개틀링 토끼 건
Name: 522, dtype: object)
(523, item_id         9177
item_name    타오르는 단궁
Name: 523, dtype: object)
(524, item_id      9178
item_name     절멸자
Name: 524, dtype: object)
(525, item_id          9179
item_name    전투 토끼 석궁
Name: 525, dtype: object)
(526, item_id         9180
item_name    귀여운 발사기
Name: 526, dtype: object)
(527, item_id         9181
item_name    소용돌이 장갑
Name: 527, dtype: object)
(528, item_id        9183
item_name    칼날 부메랑
Name: 528, dtype: object)
(529, item_id           9184
item_name    토끼 초강력 폭발
Name: 529, dtype: object)
(530, item_id            9185
item_name    상어잡이 해양 기뢰
Name: 530, dtype: object)
(531, item_id      9187
item_name      티버
Name: 531, dtype: object)
(532, item_id       9188
item_name    동물 지뢰
Name: 532, dtype: object)
(533, item_id             9189
item_name    최후의 도시 대중교통
Name: 533, dtype: object)
(534, item_id            9190
item_name    메아리치는 박쥐칼날
Name: 534, dtype: object)
(535, item_id           9192
item_name    발자국 중독 장치
Name: 535, dtype: object)
(536, item_id         9193
item_name    얼음작렬 갑옷
Name: 536, dtype: object)
(537, item_id           9271
item_name    그치지 않는 폭풍
Name: 537, dtype: object)
(538, item_id         9272
item_name    유미봇최종최종
Name: 538, dtype: object)
(539, item_id        9273
item_name    폭발의 포옹
Name: 539, dtype: object)
(540, item_id             9274
item_name    프룸비스의 전기도축칼
Name: 540, dtype: object)
(541, item_id       9275
item_name    휘감는 빛
Name: 541, dtype: object)
(542, item_id            9276
item_name    이중 깡충깡충 포화
Name: 542, dtype: object)
(543, item_id           9277
item_name    진화한 불꽃 사격
Name: 543, dtype: object)
(544, item_id        9278
item_name    동물의 종말
Name: 544, dtype: object)
(545, item_id              9279
item_name    토끼 프라임 거대 석궁
Name: 545, dtype: object)
(546, item_id           9280
item_name    왕 귀여운 발사기
Name: 546, dtype: object)
(547, item_id         9281
item_name    폭풍의 건틀릿
Name: 547, dtype: object)
(548, item_id        9283
item_name    사중 부메랑
Name: 548, dtype: object)
(549, item_id           9284
item_name    고속 토끼 속사포
Name: 549, dtype: object)
(550, item_id            9285
item_name    무한의 괴물 퇴치기
Name: 550, dtype: object)
(551, item_id            9287
item_name    티버 특대형 에디션
Name: 551, dtype: object)
(552, item_id                9288
item_name    징크스의 삼중 다이너마이트
Name: 552, dtype: object)
(553, item_id      9289
item_name    급행열차
Name: 553, dtype: object)
(554, item_id           9290
item_name    베인의 크로마칼날
Name: 554, dtype: object)
(555, item_id              9292
item_name    맨발 화학 물질 분사기
Name: 555, dtype: object)
(556, item_id       9293
item_name    완전 빙결
Name: 556, dtype: object)
(557, item_id       9300
item_name    야옹 야옹
Name: 557, dtype: object)
(558, item_id       9301
item_name    방패 타격
Name: 558, dtype: object)
(559, item_id        9302
item_name    음향의 물결
Name: 559, dtype: object)
(560, item_id        9303
item_name    족쇄 할퀴기
Name: 560, dtype: object)
(561, item_id       9304
item_name    강철 폭풍
Name: 561, dtype: object)
(562, item_id         9305
item_name    촉수 후려치기
Name: 562, dtype: object)
(563, item_id          9306
item_name    날개 달린 단검
Name: 563, dtype: object)
(564, item_id        9307
item_name    인도의 저주
Name: 564, dtype: object)
(565, item_id      9308
item_name     토끼뜀
Name: 565, dtype: object)
(566, item_id              9400
item_name    전투 고양이 총알 세례
Name: 566, dtype: object)
(567, item_id        9401
item_name    사자의 광명
Name: 567, dtype: object)
(568, item_id        9402
item_name    동물 메아리
Name: 568, dtype: object)
(569, item_id        9403
item_name    포악한 베기
Name: 569, dtype: object)
(570, item_id        9404
item_name    떠도는 폭풍
Name: 570, dtype: object)
(571, item_id       9405
item_name    곰의 강타
Name: 571, dtype: object)
(572, item_id        9406
item_name    연인의 도탄
Name: 572, dtype: object)
(573, item_id        9407
item_name    고양된 저주
Name: 573, dtype: object)
(574, item_id       9408
item_name    당근 격돌
Name: 574, dtype: object)

In [91]:

conn.commit()
cur.close()

In [51]:
import re

In [75]:
def del_tags(x):
    x = re.sub(r"<[^>]+>", " ", x)
    x = re.sub(r"[^가-힣\s]", "", x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()

In [77]:
item_df['item_name'] = item_df['item_name'].map(del_tags)
item_df

     item_id  item_name
0       1001         장화
1       1004     요정의 부적
2       1006  원기 회복의 구슬
3       1011    거인의 허리띠
4       1018    민첩성의 망토
..       ...        ...
570     9404     떠도는 폭풍
571     9405      곰의 강타
572     9406     연인의 도탄
573     9407     고양된 저주
574     9408      당근 격돌

[575 rows x 2 columns]

In [79]:
item_df.sort_values(by='item_name', key=lambda x: x.str.len(), ascending=False)

     item_id         item_name
392     3901  가차없는 포격 바다뱀 은화 닢
57      2010   굳건한 의지의 완전한 비스킷
393     3902   죽음의 여신 바다뱀 은화 닢
552     9288    징크스의 삼중 다이너마이트
85    220002     전설 원거리 딜러 아이템
..       ...               ...
94    221038                대검
508     6697                오만
44      1509                체질
305     3107                구원
0       1001                장화

[575 rows x 2 columns]

In [85]:
item_df.sort_index().to_csv('아이템사전.csv', encoding='utf-8')